# Generated by Django 4.2.10 on 2024-10-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos_candidatos/')),
                ('imagen', models.ImageField(upload_to='imagenes_candidatos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sufragante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_voto', models.CharField(choices=[('valido', 'Válido'), ('blanco', 'Blanco'), ('nulo', 'Nulo')], max_length=10)),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos', to='Votacion.candidato')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='Votacion.procesoelectoral')),
                ('sufragante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='Votacion.sufragante')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='Votacion.procesoelectoral'),
        ),
    ]
