# Generated by Django 4.2.10 on 2024-10-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoelectoral',
            name='descripcion',
            field=models.TextField(default=0.0009387351778656126),
            preserve_default=False,
        ),
    ]
