# Generated by Django 4.2.10 on 2024-10-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0002_procesoelectoral_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='tipo_voto',
            field=models.CharField(blank=True, choices=[('valido', 'Válido'), ('blanco', 'Blanco'), ('nulo', 'Nulo')], max_length=10),
        ),
    ]
