# Generated by Django 4.2.10 on 2024-10-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0004_alter_voto_fecha_voto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='logo',
        ),
        migrations.AddField(
            model_name='candidato',
            name='slogan',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
