# Generated by Django 4.2.10 on 2024-10-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votacion', '0005_remove_candidato_logo_candidato_slogan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='slogan',
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagen_slogan',
            field=models.ImageField(default=0.0011857707509881422, upload_to='imagenes_candidatos_slogan/'),
            preserve_default=False,
        ),
    ]
